language: python
python: 2.7

services:
 - docker

matrix:
  include:
  - env: FILENAME=Dockerfile.ubuntu
  - env: FILENAME=Dockerfile.debian

script:
  - docker build -t ansible-galaxy-os -f $FILENAME .
