language: python
python: 2.7

services:
 - docker

env:
  - FILENAME=Dockerfile.centos
  - FILENAME=Dockerfile.debian
  - FILENAME=Dockerfile.ubuntu

script:
  - docker build -t ansible-galaxy-os -f $FILENAME .
