---
# Install the base operating system requirements for running Galaxy

- include: system_users.yml
  when: add_system_users

- include: packages.yml
  when: install_packages

- include: docker.yml
  when: configure_docker
