---
# Install the base operating system requirements for running Galaxy

- include: system_users.yml
  when: add_system_users

- include: ubuntu/packages.yml
  when: install_packages and ansible_distribution == 'Ubuntu'

- include: ubuntu/docker.yml
  when: configure_docker and ansible_distribution == 'Ubuntu'

- include: debian/packages.yml
  when: install_packages and ansible_distribution == 'Debian'

- include: debian/docker.yml
  when: configure_docker and ansible_distribution == 'Debian'
