name: Build galaxykickstart docker image
on:
  push:
    branches-ignore:
      - master   # excludes master
env:
  IMG1: bionic
  IMG2: trusty
  IMG2: xenial
  
jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        IMG: [${{IMG1}}, ${{IMG2}}, ${{IMG3}}]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          docker build -f Dockerfile.ubuntu.${{IMG}} .
