name: Build galaxykickstart docker image
on:
  push:
    branches-ignore:
      - master   # excludes master
  
jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        img: ['bionic', 'trusty', 'xenial']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          docker build -f Dockerfile.ubuntu.${{img}} .
